### ISSUE TITLE
Drop down arrow in choose course

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#79]
![Screenshot 2019-08-13 at 11 33 08](https://user-images.githubusercontent.com/38726669/62935835-0febe880-bdc0-11e9-9b64-a6ffa46b278e.png)

There's a drop down arrow here but not on the previous enter provider name box

**Comment by fofr** [comment]
Yep, that's intentional. There's a small set of options for these courses and you can click to see them all. For providers, because there's so many, that won't be the case.

We might do some refinements to this design:
- if there's fewer than X courses, show them as radio buttons
- use this select only when there is more than X

We might also need to show the short description, consider two courses shown:
Primary (X100)
Primary (B345)

It's not clear what the difference is.

**Comment by paulrobertlloyd** [comment]
Has this now been addressed by #104, @fofr and @laurahermionetennant92?
